name: "🐞 Bug report"
description: Create a bug report to help us improve things
labels: ["bug"]
title: "[Bug Report] Your descriptive title here!"
body:
  - type: markdown
    attributes:
      value: |
        ## Important information
        ### Thank you for taking the time to fill out this bug report in a sensible way and provide us with a clear information on your "Software and Hardware-Setup" and the "Steps to reproduce" your problem!
        ### Please understand you are asking for support for the Docker-Image and Docker-Container. I'm NOT the creator of the Dedicated-Game-Server itself, i'm not involved in programming that. If you need help for that, you might want to ask here for topics related to that: https://tech.palworldgame.com/getting-started/deploy-dedicated-server
  - type: checkboxes
    id: understand-minimum-required-info
    attributes:
      label: You understand that if you dont provide clear information on your "Problem", "Software and Hardware-Setup" and the "Steps to reproduce" your issue will be closed without any help, because your not willing to do your part?
      options:
        - label: Yes i do!
          required: true
  - type: checkboxes
    id: understand-gamedev-info
    attributes:
      label: You understand that im not a Game-Dev or Game-Server-Dev and my support is primary for the Docker-Image and somewhat limited to the Game-Server?
      options:
        - label: Yes i do!
          required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: A clear and concise description of what the problem is.
      placeholder: Currently...
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired behavior
      description: Remember, im not familiar with your setup, your permission, your Docker settings and all that kind of stuff, please provide a clear description of what your desired outcome is.
      placeholder: Desired behavior ...
    validations:
      required: true
  - type: textarea
    id: screenshot-links
    attributes:
      label: Links to screenshots
      placeholder: ...
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: What steps can i do to reproduce your problem?
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: software
    attributes:
      label: Software setup
      value: |
        - OS:
        - Docker:
    validations:
      required: true
  - type: textarea
    id: hardware
    attributes:
      label: Hardware setup
      value: |
        - vCPU: 
        - RAM: 
        - Disk:
    validations:
      required: true
  - type: textarea
    id: more
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here, in as much detail as possible.
    validations:
      required: false
